app/webpage/auth.py
import os
from authlib.common.security import generate_token
from werkzeug.security import generate_password_hash, check_password_hash
from flask import render_template, Blueprint, request, flash, redirect, url_for, session
from flask import current_app as app

auth_bp = Blueprint(
    "auth_bp", "__name__", template_folder="templates", static_folder="static"
)


# Define a rota para a página de registro
@auth_bp.post("/register")
def register_post():
    # Obtém o usuário, a senha e o email informados no formulário
    username = request.form.get("username")
    password = request.form.get("password")
    email = request.form.get("email")

    # Verifica se o email já existe na coleção de usuários
    email_found = app.db.users.find_one({"email": email})
    username_found = app.db.users.find_one({"username": username})

    if email_found is not None:
        flash("Esse email já foi cadastrado.")
        return render_template("register.html", title="Registrar")

    if username_found is not None:
        flash("Esse nome de usuário já está em uso.")
        return render_template("register.html", title="Registrar")

    hashed_password = generate_password_hash(password)
    # Insere o novo usuário na coleção de usuários, se nome de usuário e email estão disponíveis
    app.db.users.insert_one(
        {
            "username": username,
            "password": hashed_password,
            "email": email,
            "role": "user",
        }
    )

    # Cria uma coleção específica para o usuário com um documento inicial
    userfound = app.db.users.find_one({"username": username})
    user_collection_name=f"data_{userfound['_id']}"
    app.db[user_collection_name].insert_one(
        {"message": f"Coleção criada para o usuário {username}."}
    )

    # Redireciona para a página de login após o registro bem-sucedido
    flash("Registro bem-sucedido! Faça o login para continuar.")
    return redirect(url_for("auth_bp.login_get", title="Login"))


@auth_bp.get("/register")
def register_get():
    if "username" in session:
        return redirect(url_for("index_bp.index_get"))
    else:
        return render_template("register.html", session=False, title="Registrar")


# Define a rota para a página de login
@auth_bp.post("/login")
def login_post():
    # Obtém o usuário e a senha informados no formulário
    username = request.form["username"]
    password = request.form["password"]
    userfound = app.db.users.find_one({"username": username})

    if userfound and check_password_hash(userfound["password"], password):
        session["username"] = username
        return redirect(url_for("index_bp.index_get"))
    else:
        # Se as credenciais estiverem incorretas, exibe uma mensagem de erro
        flash("Usuário ou senha incorretos.")
        return render_template("login.html", session=False, title="Login")


@auth_bp.get("/login")
def login_get():
    # Se a requisição for GET, exibe a página de login
    if "username" in session:
        return redirect(url_for("index_bp.index_get"))
    else:
        return render_template("login.html", session=False, title="Login")


# autenticação google
@auth_bp.route("/google/")
def google():

    GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
    GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]

    CONF_URL = "https://accounts.google.com/.well-known/openid-configuration"
    app.oauth.register(
        name="google",
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        server_metadata_url=CONF_URL,
        client_kwargs={"scope": "openid email profile"},
    )

    # Redirect to google_auth function
    redirect_uri = url_for("auth_bp.google_auth", _external=True)
    session["nonce"] = generate_token()
    return app.oauth.google.authorize_redirect(redirect_uri, nonce=session["nonce"])


@auth_bp.route("/google/auth/")
def google_auth():
    token = app.oauth.google.authorize_access_token()
    user = app.oauth.google.parse_id_token(token, nonce=session["nonce"])
    username = user["name"]
    email = user["email"]
    password = user["sub"]

    # Verifica se o usuário já existe
    userfound = app.db.users.find_one({"email": email})
    if userfound == None:
        app.db.users.insert_one(
            {"username": username, "password": password, "email": email, "data": {}}
        )
    session["username"] = username
    return redirect("/")


# Define a rota para o logout
@auth_bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index_bp.index_get"))

app/templates/data_analysis.html
{% extends "base.html" %}

{% block head %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/data_analysis.css') }}">

{% endblock %}

{% block content %}
  <div class="d-flex flex-column w-100 pe-1 align-items-center adjust-side-menu" style="text-align: center; min-height: 100vh">
    <!-- menu inicial -->
    {% if not model %}
      <p class="fs-3 fw-bold my-0 py-2 ps-3 text-white bg-body-tertiary w-100 ">Escolha uma análise</p>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <p class="fs-3  fw-semibold my-0 py-2 pt-3 text-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        <a href="{{ url_for('data_bp.dataanalysis_get', username=username, model='bertimbau') }}" aria-current="true" class="text-decoration-none">
          <div class="btn d-flex text-with-shadow flex-column bg-body-tertiary me-md-3 my-0 py-0 pt-3 px-3 px-md-3 text-center overflow-hidden border-0" style="height: 80vh;">
            <div class="my-3 p-3 align-self-start">
              <h2 class="display-5">BERTimbau</h2>
              <p class="lead">Descubra insights profundos através da Análise de Sentimentos por Processamento de Linguagem Natural (NLP).</p>
            </div>
            <div class="d-flex bg-dark shadow-sm mx-auto justify-content-center mt-auto align-self-end align-items-center" style="width: 100%; height: 240px; border-radius: 21px 21px 0 0;">
              <img src="{{ url_for('static', filename='bertimbau.svg')}}" class="img-fluid" style="width: auto; height: 200px;">
            </div>
          </div>
        </a>
        <a href="{{ url_for('data_bp.dataanalysis_get', username=username, model='kmeans') }}" aria-current="true" class="text-decoration-none">
          <div class="btn d-flex text-with-shadow flex-column bg-body-tertiary me-md-3 my-0 py-0 pt-3 px-3 px-md-3 text-center overflow-hidden border-0 disabled" style="height: 80vh;">
            <div class="my-3 p-3 align-self-start">
              <h2 class="display-5">K-Means</h2>
              <p class="lead">Explore a análise de dados com K-Means! Descubra padrões e insights Valiosos para sua avaliação de UX.</p>
            </div>
            <div class="d-flex bg-dark shadow-sm mx-auto justify-content-center mt-auto align-self-end align-items-center" style="width: 100%; height: 240px; border-radius: 21px 21px 0 0;">
              <img src="{{ url_for('static', filename='kmeans.svg')}}" class="img-fluid" style="width: auto; height: 200px;">
            </div>
          </div>
        </a>
        <a href="{{ url_for('data_bp.dataanalysis_get', username=username, model='meanshift') }}" aria-current="true" class="text-decoration-none">
          <div class="btn d-flex text-with-shadow flex-column bg-body-tertiary me-md-3 my-0 py-0 pt-3 px-3 px-md-3 text-center overflow-hidden border-0 disabled" style="height: 80vh;">
            <div class="my-3 p-3 align-self-start">
              <h2 class="display-5">Meanshift</h2>
              <p class="lead">Desvende padrões complexos com MeanShift! Explore uma análise avançada e revele insights surpreendentes!</p>
            </div>
            <div class="d-flex bg-dark shadow-sm mx-auto justify-content-center mt-auto align-self-end align-items-center" style="width: 100%; height: 240px; border-radius: 21px 21px 0 0;">
              <img src="{{ url_for('static', filename='meanshift.svg')}}" class="img-fluid" style="width: auto; height: 200px;">
            </div>
          </div>
        </a>
      </div>
    
    <!-- seleção do dado -->
    {% else %}
      <!-- popup de resultado -->
      <div class="modal modal-xl fade" id="resultModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="resultModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <h5 class="modal-title w-100" id="resultModalLabel">Resultado</h5>
              <button type="button" onclick="closePopupResult()" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="list-group modal-body align-items-center justify-content-center gap-3 w-100" style="text-align: center;">
              <div class="list-group-item border-0 w-100">
                <div class="spinner-border text-secondary" id="spinner" role="status"></div>
                <div  id="resultplot"></div>
                <button type="button" onclick="clickbutton()" id="mybutton" class="btn btn-secondary mt-3" style="width: 250px">Baixar</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="list-group flex-lg-column w-100">
        <p class="fs-3 fw-semibold my-0 py-2 ps-3 text-white bg-body-tertiary w-100">Selecione a coleta que irá processar com o modelo {{ model|capitalize }}</p>
        {% for data in items%}
          <a href="javascript:;" onclick="submitdata(this.getAttribute('data-value'), this.getAttribute('url_data'), this.getAttribute('url_audio'))" data-value="{{ data['id'] }}"  url_data="{{url_for('data_bp.dataanalysis_post', username=username, model=model)}}" url_audio="{{url_for('data_bp.downloadAudio')}}" class="list-group-item align-items-center list-group-item-action d-flex gap-3 py-3 cor-preto1" aria-current="true">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
                  <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                  <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
              </svg>
              <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                <h6 class="mb-1">Dia: {{ data['date'] }}</h6>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi me-2 bi-clock-history" viewBox="0 0 16 16">
                    <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                    <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                    <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                  </svg><span class="mb-0 opacity-75">Às {{ data['time'] }}</span>
                </div>
                <div>
                    <h6 class="mb-2 w-100 text-white" style="text-align: end;">Páginas coletadas</h6>
                    {% for page in data['sites'] %}
                        <small class="text-bg-light opacity-100 text-nowrap border px-2 py-1 ms-1 rounded-pill custom-style">{{ page }}</small>
                    {% endfor %}
                </div>
              </div>
            </a>
        {% endfor %}

        <div class="mt-4 ml-4 mx-4">
          {% if page_obj.has_other_pages() %}
          <ul class="pagination">
              {% if page_obj.number != 1%}
                <li class="page-item">
                  <a class="page-link text-body-secondary" href="{{ url_for('data_bp.dataanalysis_get', username=username, model=model, page_number=1)}}">Início</a>
                </li>
              {% else %}
                <li class="page-link text-body-secondary disabled">Início</li>
              {% endif %}

            {% for i in page_obj.paginator.page_range %}
              {% if i >= page_obj.number - 2 and i <= page_obj.number + 2 %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link text-body-secondary" href="{{ url_for('data_bp.dataanalysis_get', username=username, model=model, page_number=i) }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.number != page_obj.paginator.num_pages%}
              <li class="page-item">
              <a class="page-link text-body-secondary" href="{{ url_for('data_bp.dataanalysis_get', username=username, model=model, page_number=page_obj.paginator.num_pages)}}">Final</a></li>
            {% else %}
              <li class="page-link text-body-secondary disabled">Final</li>
            {% endif %}
          </ul>
          {% endif %}
        </div>

        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <p>{{ message }}</p>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
    {% endif %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="{{ url_for('static', filename='js/data_analysis.js')}}"></script>
{% endblock %}
  

app/templates/email.html
<!DOCTYPE html>
<html>

<head>
	<title>Teste serviço Geometa</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/email.css') }}">
</head>

<body style="background-color: rgb(36, 36, 36); text-align: center;">
	<section>
		<img style="width: 13%; margin: auto; padding: 3em;" src="{{ url_for('static', filename='logo.png' )}}" alt="UX-Tracking Logo">
        <br>
		<h1 style="color: whitesmoke">User eXperience Tracking</h1>
        <br>
        <p style="color: white">Dear {{ username }},</p>
        <br>
        <p>We are sending you this message because you have been asked to reset your password on our platform, the new password generated for your account is below:</p>

        <div class="block">
			<h1>Serviço de processamento de imagens</h1><br>
			<form action="http://127.0.0.1:5000/receiver" method="POST" enctype="multipart/form-data">
				<input type="file" name="image" id="image"><br><br>
				<label for="image">
					<i class="glyphicon glyphico-open"></i>
					&nbsp;Escolher um arquivo
				</label><br><br><br>
				<span>
					<strong>Arquivo escolhido:</strong>
					<span id="image-chosen">None</span>
				</span>
				<button type="submit">ENVIAR</button>
			</form>
		</div>
	</section>
</body>

</html>

app/templates/erro.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Erro {{erro}}</title>
    <link rel="shortcut icon" type="imagex/png" href="{{ url_for('static', filename='icon.svg') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/erro.css') }}">
</head>
<body>
    <!-- <header>
        <div class="px-3 py-2 d-flex flex-wrap align-items-center justify-content-lg-start text-center text-bg-dark " style="min-height: 10vh;">
            <img class="bi me-2" src="{{ url_for('static', filename='logo.png') }}" alt="" width="auto" height="50">
            <span class="fs-5 text-light fw-bolder">UX-Tracking</span>
        </div>
    </header> -->
    <main class="apresentacao">
        <img src="{{url_for('static', filename='error-page.png')}}" alt="error icon" width="350" height="350">
        <section class="apresentacao__conteudo">
            <p class="apresentacao__conteudo__titulo display-6 fw-bold lh-1 mb-3">Erro {{erro}}</p>
            <p class="apresentacao__conteudo__texto lead">{{message}}</p>
            <P class="apresentacao__conteudo__texto lead">Se desejar obter mais informações ou relatar o erro, por favor, entre em contato conosco através do e-mail <a class="apresentacao__conteudo__link lead" href="mailto:uxtracking.service@gmail.com">uxtracking.service@gmail.com</a></P>
            <p class="apresentacao__conteudo__texto lead">Você pode retornar à página inicial clicando no link: <a class="apresentacao__conteudo__link lead" href="{{url_for('index_bp.index_get')}}">Voltar para Página Inicial</a></p>
        </section>
    </main>
</body>
</html>

app/templates/forgot_pass.html
{% extends "base.html" %}

{% block head %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/forgot_pass.css') }}">

{% endblock %}

{% block content %}
  <div class="container col-xxl-8 px-5 py-5" style="min-height: 80vh;">
    <div class="row flex-lg-row align-items-center g-5 py-4">
        <div class="col-10 col-sm-8 col-lg-6">
          <h1 class="display-6 fw-bold text-body-emphasis lh-1 mb-3">Esqueceu sua senha? Não tem problema</h1>
            <p class="lead">Preencha suas informações para receber um email com sua nova senha de acesso à nossa plataforma, recomendamos fazer a alteração da nova senha assim que possível.</p>
        </div>
        <div class="col-lg-6">
          <div class="form-signin justify-content-center w-100 m-auto">    
            <form method="POST">

              <h1 class="h2 mb-4 mt-5 fw-normal" style="text-align: center;">Recuperar a senha</h1>
              
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                {% endif %}
              {% endwith %}

              <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="User123Example">
                <label for="floatingInput">Nome de usuário</label>
              </div>
              <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="example@email.com">
                <label for="floatingInput">Email</label>
              </div>

              <button class="btn btn-primary w-100 py-2" type="submit" style="color: white;">Receber minha senha por email</button>

              <p style="text-align: center;"><br>
                <a href="{{ url_for('auth_bp.login_get') }}">Tem uma conta?</a><br>
                <a href="{{ url_for('auth_bp.register_get') }}">Não tem uma conta?</a>
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block head %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">

{% endblock %}


{% block content %} 
<div class="mt-5">
  <div class="container mt-5" style="width: 79%; min-height:77vh">
    <div class="row mt-5 gx-5">
      <div class="col-sm-7 mt-5">
        <h1 class="display-6 fw-bold text-body-emphasis lh-1 mb-3">Acesse uma variedade de funcionalides para avaliação de UX</h1>
        <p class="lead" style="text-align: justify;">Entre na sua conta para acessar seus dados coletados com a extensão UX-Tracking, realizar o
          processamento dos traços coletados e avaliações visuais das interações dos usuários. E se ainda tiver dúvidas,
          basta acessar nossa documentação disponível na nossa plataforma.</p>
      </div>
      <div class="col-sm-5 ms-auto custom-col-center">
        <div class="form-signin justify-content-end w-100 ">
          <form method="POST">
            
            <h1 class="h2 my-4 fw-normal" style="text-align: center;">Faça o login</h1>
            
            <div class="form-floating">
              <input type="text" name="username" class="form-control" id="floatingInput" placeholder="User123Example">
              <label for="floatingInput">Nome de usuário</label>
            </div>
            <div class="form-floating">
              <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
              <label for="floatingPassword">Senha</label>
            </div>
            
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <p style="color: red;">{{ message }}</p>
            <style>
              .form-control {
                border-color: red;
              }
              .form-control:focus {
                border-color: red;
                box-shadow: 0 0 0 0.3rem rgba(255, 0, 0, 0.25);
              }
            </style>
            {% endfor %}
            {% endif %}
            {% endwith %}
            
            <button class="btn btn-primary w-100 py-2 my-3 text-white" type="submit">Login</button>
            <!-- desativado
            <h1 class="h5 mb-3 fw-normal" style="text-align: center;">ou</h1>

            
            <div style="text-align:center">
              <a href="{{ url_for('auth_bp.google') }}">
                <button type="button" class="login-with-google-btn">
                  Faça login com o Google
                </button>
              </a>
            </div> -->

            <p style="text-align: center;"><br>
              <a href="{{ url_for('pass_bp.forgot_pass_get') }}">Esqueceu a senha?</a><br>
              <a href="{{ url_for('auth_bp.register_get') }}">Não tem uma conta?</a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block head %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">

{% endblock %}

{% block content %}
<div class="mt-5">
  <div class="container minha-div mt-5" style="width: 79%; min-height:77vh">
    <div class="row mt-5">
      <div class="col-sm-7 mt-5" >
        <div class="justify-content-center mt-2 align-items-center">
          <h1 class="display-6 fw-bold text-body-emphasis justify-content-center lh-1 mb-3" >Obtenha o acesso a todas as funcionalides do UX-Tracking</h1>
          <p class="lead" style="text-align: justify;">Realize seu cadastro para obter a extensão de captura de dados multimodal da UX-Tracking e uma variedade de funcionalidades para aprimorar sua avaliação de UX. Preencha suas informações para obter acesso imediato a nossa plataforma e o download da extensão.</p>
        </div>
      </div>
      <div class="col-sm-5">
          <div class="form-signup justify-content-center w-100 m-auto">    
            <form method="POST">
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                {% endif %}
              {% endwith %}

              <h1 class="h2 my-4 fw-normal" style="text-align: center;">Faça o registro</h1>

              <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="User123Example">
                <label for="floatingInput">Nome de usuário</label>
              </div>
              <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="example@email.com">
                <label for="floatingPassword">Endereço de email</label>
              </div>
              <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password" style="
                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;
                border-top-left-radius: 0;
                border-top-right-radius: 0;">
                <label for="floatingPassword">Senha</label>
              </div>
              <div class="form-floating">
                <input type="password" name="confirm_password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Confirme sua senha</label>
              </div>

              <button class="btn btn-primary w-100 py-2 my-3 text-white" type="submit">Registrar</button>

              <!-- desativado
              <h1 class="h4 mb-3 fw-normal" style="text-align: center;">ou</h1>
              
              <div style="text-align:center">
                <a href="{{ url_for('auth_bp.google') }}">
                  <button type="button" class="login-with-google-btn">
                    Registre-se com o Google
                  </button>
                </a>
              </div>
            -->
              <p class="mt-n1" style="text-align: center;"><br>
                <a href="{{ url_for('pass_bp.forgot_pass_get') }}">Esqueceu sua senha?</a><br>
                <a href="{{ url_for('auth_bp.login_get') }}">Já tem conta?</a>
              </p>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}